### PR TITLE
add a simple benchmark suite

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by andrewthad** [comment]
Resolves https://github.com/chessai/is-utf8-bytestring/issues/5

**Comment by andrewthad** [comment]
As expected, this shows the naive check that all characters belong in the ascii plane to be 8 times slower than the vectorized version (on a 64-bit platform).

**Comment by chessai** [comment]
Dangit, Drew, I was just writing this.

**Comment by andrewthad** [comment]
Also, you probably want to use `gauge` instead of `criterion`. It's just a clone of `criterion` but with all the graphical stuff stripped out. I keep meaning to use this in new stuff but keep forgetting.

**Comment by chessai** [comment]
Alright.

**Pull request merged**
